<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateTransfer;

/**
 * Builder for model CreateTransfer
 *
 * @see CreateTransfer
 */
class CreateTransferBuilder
{
    /**
     * @var CreateTransfer
     */
    private $instance;

    private function __construct(CreateTransfer $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create transfer Builder object.
     */
    public static function init(int $amount, string $sourceId, string $targetId): self
    {
        return new self(new CreateTransfer($amount, $sourceId, $targetId));
    }

    /**
     * Sets metadata field.
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Initializes a new create transfer object.
     */
    public function build(): CreateTransfer
    {
        return CoreHelper::clone($this->instance);
    }
}
