<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateCancelChargeSplitRulesRequest;

/**
 * Builder for model CreateCancelChargeSplitRulesRequest
 *
 * @see CreateCancelChargeSplitRulesRequest
 */
class CreateCancelChargeSplitRulesRequestBuilder
{
    /**
     * @var CreateCancelChargeSplitRulesRequest
     */
    private $instance;

    private function __construct(CreateCancelChargeSplitRulesRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create cancel charge split rules request Builder object.
     */
    public static function init(string $id, int $amount, string $type): self
    {
        return new self(new CreateCancelChargeSplitRulesRequest($id, $amount, $type));
    }

    /**
     * Initializes a new create cancel charge split rules request object.
     */
    public function build(): CreateCancelChargeSplitRulesRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
