<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateBankAccountRefundingDTO;

/**
 * Builder for model CreateBankAccountRefundingDTO
 *
 * @see CreateBankAccountRefundingDTO
 */
class CreateBankAccountRefundingDTOBuilder
{
    /**
     * @var CreateBankAccountRefundingDTO
     */
    private $instance;

    private function __construct(CreateBankAccountRefundingDTO $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create bank account refunding dto Builder object.
     */
    public static function init(
        string $holderName,
        string $holderType,
        string $holderDocument,
        string $bank,
        string $branchNumber,
        string $branchCheckDigit,
        string $accountNumber,
        string $accountCheckDigit,
        string $type
    ): self {
        return new self(new CreateBankAccountRefundingDTO(
            $holderName,
            $holderType,
            $holderDocument,
            $bank,
            $branchNumber,
            $branchCheckDigit,
            $accountNumber,
            $accountCheckDigit,
            $type
        ));
    }

    /**
     * Initializes a new create bank account refunding dto object.
     */
    public function build(): CreateBankAccountRefundingDTO
    {
        return CoreHelper::clone($this->instance);
    }
}
