<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreatePaymentLinkInstallmentRequest;

/**
 * Builder for model CreatePaymentLinkInstallmentRequest
 *
 * @see CreatePaymentLinkInstallmentRequest
 */
class CreatePaymentLinkInstallmentRequestBuilder
{
    /**
     * @var CreatePaymentLinkInstallmentRequest
     */
    private $instance;

    private function __construct(CreatePaymentLinkInstallmentRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Payment Link Installment Request Builder object.
     *
     * @param int $number
     * @param int $total
     */
    public static function init(int $number, int $total): self
    {
        return new self(new CreatePaymentLinkInstallmentRequest($number, $total));
    }

    /**
     * Initializes a new Create Payment Link Installment Request object.
     */
    public function build(): CreatePaymentLinkInstallmentRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
