<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateAntifraudRequest;
use PagarmeApiSDKLib\Models\CreateChargeRequest;
use PagarmeApiSDKLib\Models\CreateCustomerRequest;
use PagarmeApiSDKLib\Models\CreatePaymentRequest;

/**
 * Builder for model CreateChargeRequest
 *
 * @see CreateChargeRequest
 */
class CreateChargeRequestBuilder
{
    /**
     * @var CreateChargeRequest
     */
    private $instance;

    private function __construct(CreateChargeRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create charge request Builder object.
     */
    public static function init(
        string $code,
        int $amount,
        string $customerId,
        CreateCustomerRequest $customer,
        CreatePaymentRequest $payment,
        array $metadata,
        CreateAntifraudRequest $antifraud,
        string $orderId
    ): self {
        return new self(
            new CreateChargeRequest(
                $code,
                $amount,
                $customerId,
                $customer,
                $payment,
                $metadata,
                $antifraud,
                $orderId
            )
        );
    }

    /**
     * Sets due at field.
     */
    public function dueAt(?\DateTime $value): self
    {
        $this->instance->setDueAt($value);
        return $this;
    }

    /**
     * Initializes a new create charge request object.
     */
    public function build(): CreateChargeRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
