<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreatePaymentLinkCartSettingsRequest;
use PagarmeApiSDKLib\Models\CreatePaymentLinkCustomerSettingsRequest;
use PagarmeApiSDKLib\Models\CreatePaymentLinkPaymentSettingsRequest;
use PagarmeApiSDKLib\Models\CreatePaymentLinkRequest;

/**
 * Builder for model CreatePaymentLinkRequest
 *
 * @see CreatePaymentLinkRequest
 */
class CreatePaymentLinkRequestBuilder
{
    /**
     * @var CreatePaymentLinkRequest
     */
    private $instance;

    private function __construct(CreatePaymentLinkRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Payment Link Request Builder object.
     *
     * @param string $type
     * @param CreatePaymentLinkPaymentSettingsRequest $paymentSettings
     * @param CreatePaymentLinkCartSettingsRequest $cartSettings
     */
    public static function init(
        string $type,
        CreatePaymentLinkPaymentSettingsRequest $paymentSettings,
        CreatePaymentLinkCartSettingsRequest $cartSettings
    ): self {
        return new self(new CreatePaymentLinkRequest($type, $paymentSettings, $cartSettings));
    }

    /**
     * Sets is building field.
     *
     * @param bool|null $value
     */
    public function isBuilding(?bool $value): self
    {
        $this->instance->setIsBuilding($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets expires in field.
     *
     * @param int|null $value
     */
    public function expiresIn(?int $value): self
    {
        $this->instance->setExpiresIn($value);
        return $this;
    }

    /**
     * Sets expires at field.
     *
     * @param \DateTime|null $value
     */
    public function expiresAt(?\DateTime $value): self
    {
        $this->instance->setExpiresAt($value);
        return $this;
    }

    /**
     * Sets max sessions field.
     *
     * @param int|null $value
     */
    public function maxSessions(?int $value): self
    {
        $this->instance->setMaxSessions($value);
        return $this;
    }

    /**
     * Sets max paid sessions field.
     *
     * @param int|null $value
     */
    public function maxPaidSessions(?int $value): self
    {
        $this->instance->setMaxPaidSessions($value);
        return $this;
    }

    /**
     * Sets customer settings field.
     *
     * @param CreatePaymentLinkCustomerSettingsRequest|null $value
     */
    public function customerSettings(?CreatePaymentLinkCustomerSettingsRequest $value): self
    {
        $this->instance->setCustomerSettings($value);
        return $this;
    }

    /**
     * Initializes a new Create Payment Link Request object.
     */
    public function build(): CreatePaymentLinkRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
