<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreatePhoneRequest;

/**
 * Builder for model CreatePhoneRequest
 *
 * @see CreatePhoneRequest
 */
class CreatePhoneRequestBuilder
{
    /**
     * @var CreatePhoneRequest
     */
    private $instance;

    private function __construct(CreatePhoneRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create phone request Builder object.
     */
    public static function init(): self
    {
        return new self(new CreatePhoneRequest());
    }

    /**
     * Sets country code field.
     */
    public function countryCode(?string $value): self
    {
        $this->instance->setCountryCode($value);
        return $this;
    }

    /**
     * Sets number field.
     */
    public function number(?string $value): self
    {
        $this->instance->setNumber($value);
        return $this;
    }

    /**
     * Sets area code field.
     */
    public function areaCode(?string $value): self
    {
        $this->instance->setAreaCode($value);
        return $this;
    }

    /**
     * Initializes a new create phone request object.
     */
    public function build(): CreatePhoneRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
