<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateCheckoutPixPaymentRequest;

/**
 * Builder for model CreateCheckoutPixPaymentRequest
 *
 * @see CreateCheckoutPixPaymentRequest
 */
class CreateCheckoutPixPaymentRequestBuilder
{
    /**
     * @var CreateCheckoutPixPaymentRequest
     */
    private $instance;

    private function __construct(CreateCheckoutPixPaymentRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create checkout pix payment request Builder object.
     */
    public static function init(): self
    {
        return new self(new CreateCheckoutPixPaymentRequest());
    }

    /**
     * Sets expires at field.
     */
    public function expiresAt(?\DateTime $value): self
    {
        $this->instance->setExpiresAt($value);
        return $this;
    }

    /**
     * Sets expires in field.
     */
    public function expiresIn(?int $value): self
    {
        $this->instance->setExpiresIn($value);
        return $this;
    }

    /**
     * Sets additional information field.
     */
    public function additionalInformation(?array $value): self
    {
        $this->instance->setAdditionalInformation($value);
        return $this;
    }

    /**
     * Initializes a new create checkout pix payment request object.
     */
    public function build(): CreateCheckoutPixPaymentRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
