<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateCaptureChargeRequest;

/**
 * Builder for model CreateCaptureChargeRequest
 *
 * @see CreateCaptureChargeRequest
 */
class CreateCaptureChargeRequestBuilder
{
    /**
     * @var CreateCaptureChargeRequest
     */
    private $instance;

    private function __construct(CreateCaptureChargeRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create capture charge request Builder object.
     */
    public static function init(string $code, string $operationReference): self
    {
        return new self(new CreateCaptureChargeRequest($code, $operationReference));
    }

    /**
     * Sets amount field.
     */
    public function amount(?int $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Sets split field.
     */
    public function split(?array $value): self
    {
        $this->instance->setSplit($value);
        return $this;
    }

    /**
     * Initializes a new create capture charge request object.
     */
    public function build(): CreateCaptureChargeRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
