<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateBankAccountRequest;
use PagarmeApiSDKLib\Models\CreateRecipientRequest;
use PagarmeApiSDKLib\Models\CreateTransferSettingsRequest;

/**
 * Builder for model CreateRecipientRequest
 *
 * @see CreateRecipientRequest
 */
class CreateRecipientRequestBuilder
{
    /**
     * @var CreateRecipientRequest
     */
    private $instance;

    private function __construct(CreateRecipientRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create recipient request Builder object.
     */
    public static function init(
        string $name,
        string $email,
        string $description,
        string $document,
        string $type,
        CreateBankAccountRequest $defaultBankAccount,
        array $metadata,
        string $code,
        string $paymentMode
    ): self {
        return new self(new CreateRecipientRequest(
            $name,
            $email,
            $description,
            $document,
            $type,
            $defaultBankAccount,
            $metadata,
            $code,
            $paymentMode
        ));
    }

    /**
     * Sets transfer settings field.
     */
    public function transferSettings(?CreateTransferSettingsRequest $value): self
    {
        $this->instance->setTransferSettings($value);
        return $this;
    }

    /**
     * Initializes a new create recipient request object.
     */
    public function build(): CreateRecipientRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
