<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateCustomerRequest;
use PagarmeApiSDKLib\Models\CreatePaymentLinkCustomerSettingsRequest;

/**
 * Builder for model CreatePaymentLinkCustomerSettingsRequest
 *
 * @see CreatePaymentLinkCustomerSettingsRequest
 */
class CreatePaymentLinkCustomerSettingsRequestBuilder
{
    /**
     * @var CreatePaymentLinkCustomerSettingsRequest
     */
    private $instance;

    private function __construct(CreatePaymentLinkCustomerSettingsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Payment Link Customer Settings Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CreatePaymentLinkCustomerSettingsRequest());
    }

    /**
     * Sets customer id field.
     *
     * @param string|null $value
     */
    public function customerId(?string $value): self
    {
        $this->instance->setCustomerId($value);
        return $this;
    }

    /**
     * Sets customer field.
     *
     * @param CreateCustomerRequest|null $value
     */
    public function customer(?CreateCustomerRequest $value): self
    {
        $this->instance->setCustomer($value);
        return $this;
    }

    /**
     * Initializes a new Create Payment Link Customer Settings Request object.
     */
    public function build(): CreatePaymentLinkCustomerSettingsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
