<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateCardPaymentContactlessPOIRequest;
use PagarmeApiSDKLib\Models\CreateEmvDataDecryptRequest;
use PagarmeApiSDKLib\Models\CreateEmvDecryptRequest;

/**
 * Builder for model CreateEmvDecryptRequest
 *
 * @see CreateEmvDecryptRequest
 */
class CreateEmvDecryptRequestBuilder
{
    /**
     * @var CreateEmvDecryptRequest
     */
    private $instance;

    private function __construct(CreateEmvDecryptRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create emv decrypt request Builder object.
     */
    public static function init(string $iccData, string $cardSequenceNumber, CreateEmvDataDecryptRequest $data): self
    {
        return new self(new CreateEmvDecryptRequest($iccData, $cardSequenceNumber, $data));
    }

    /**
     * Sets poi field.
     */
    public function poi(?CreateCardPaymentContactlessPOIRequest $value): self
    {
        $this->instance->setPoi($value);
        return $this;
    }

    /**
     * Initializes a new create emv decrypt request object.
     */
    public function build(): CreateEmvDecryptRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
