<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetFineResponse;

/**
 * Builder for model GetFineResponse
 *
 * @see GetFineResponse
 */
class GetFineResponseBuilder
{
    /**
     * @var GetFineResponse
     */
    private $instance;

    private function __construct(GetFineResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new get fine response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetFineResponse());
    }

    /**
     * Sets days field.
     */
    public function days(?int $value): self
    {
        $this->instance->setDays($value);
        return $this;
    }

    /**
     * Unsets days field.
     */
    public function unsetDays(): self
    {
        $this->instance->unsetDays();
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Unsets type field.
     */
    public function unsetType(): self
    {
        $this->instance->unsetType();
        return $this;
    }

    /**
     * Sets amount field.
     */
    public function amount(?int $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Unsets amount field.
     */
    public function unsetAmount(): self
    {
        $this->instance->unsetAmount();
        return $this;
    }

    /**
     * Initializes a new get fine response object.
     */
    public function build(): GetFineResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
