<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetGatewayResponseResponse;

/**
 * Builder for model GetGatewayResponseResponse
 *
 * @see GetGatewayResponseResponse
 */
class GetGatewayResponseResponseBuilder
{
    /**
     * @var GetGatewayResponseResponse
     */
    private $instance;

    private function __construct(GetGatewayResponseResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new get gateway response response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetGatewayResponseResponse());
    }

    /**
     * Sets code field.
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Unsets code field.
     */
    public function unsetCode(): self
    {
        $this->instance->unsetCode();
        return $this;
    }

    /**
     * Sets errors field.
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Unsets errors field.
     */
    public function unsetErrors(): self
    {
        $this->instance->unsetErrors();
        return $this;
    }

    /**
     * Initializes a new get gateway response response object.
     */
    public function build(): GetGatewayResponseResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
