<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetPricingSchemeResponse;

/**
 * Builder for model GetPricingSchemeResponse
 *
 * @see GetPricingSchemeResponse
 */
class GetPricingSchemeResponseBuilder
{
    /**
     * @var GetPricingSchemeResponse
     */
    private $instance;

    private function __construct(GetPricingSchemeResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new get pricing scheme response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetPricingSchemeResponse());
    }

    /**
     * Sets price field.
     */
    public function price(?int $value): self
    {
        $this->instance->setPrice($value);
        return $this;
    }

    /**
     * Unsets price field.
     */
    public function unsetPrice(): self
    {
        $this->instance->unsetPrice();
        return $this;
    }

    /**
     * Sets scheme type field.
     */
    public function schemeType(?string $value): self
    {
        $this->instance->setSchemeType($value);
        return $this;
    }

    /**
     * Unsets scheme type field.
     */
    public function unsetSchemeType(): self
    {
        $this->instance->unsetSchemeType();
        return $this;
    }

    /**
     * Sets price brackets field.
     */
    public function priceBrackets(?array $value): self
    {
        $this->instance->setPriceBrackets($value);
        return $this;
    }

    /**
     * Unsets price brackets field.
     */
    public function unsetPriceBrackets(): self
    {
        $this->instance->unsetPriceBrackets();
        return $this;
    }

    /**
     * Sets minimum price field.
     */
    public function minimumPrice(?int $value): self
    {
        $this->instance->setMinimumPrice($value);
        return $this;
    }

    /**
     * Unsets minimum price field.
     */
    public function unsetMinimumPrice(): self
    {
        $this->instance->unsetMinimumPrice();
        return $this;
    }

    /**
     * Sets percentage field.
     */
    public function percentage(?float $value): self
    {
        $this->instance->setPercentage($value);
        return $this;
    }

    /**
     * Unsets percentage field.
     */
    public function unsetPercentage(): self
    {
        $this->instance->unsetPercentage();
        return $this;
    }

    /**
     * Initializes a new get pricing scheme response object.
     */
    public function build(): GetPricingSchemeResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
