<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetAddressResponse;
use PagarmeApiSDKLib\Models\GetShippingResponse;

/**
 * Builder for model GetShippingResponse
 *
 * @see GetShippingResponse
 */
class GetShippingResponseBuilder
{
    /**
     * @var GetShippingResponse
     */
    private $instance;

    private function __construct(GetShippingResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new get shipping response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetShippingResponse());
    }

    /**
     * Sets amount field.
     */
    public function amount(?int $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Unsets amount field.
     */
    public function unsetAmount(): self
    {
        $this->instance->unsetAmount();
        return $this;
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Unsets description field.
     */
    public function unsetDescription(): self
    {
        $this->instance->unsetDescription();
        return $this;
    }

    /**
     * Sets recipient name field.
     */
    public function recipientName(?string $value): self
    {
        $this->instance->setRecipientName($value);
        return $this;
    }

    /**
     * Unsets recipient name field.
     */
    public function unsetRecipientName(): self
    {
        $this->instance->unsetRecipientName();
        return $this;
    }

    /**
     * Sets recipient phone field.
     */
    public function recipientPhone(?string $value): self
    {
        $this->instance->setRecipientPhone($value);
        return $this;
    }

    /**
     * Unsets recipient phone field.
     */
    public function unsetRecipientPhone(): self
    {
        $this->instance->unsetRecipientPhone();
        return $this;
    }

    /**
     * Sets address field.
     */
    public function address(?GetAddressResponse $value): self
    {
        $this->instance->setAddress($value);
        return $this;
    }

    /**
     * Unsets address field.
     */
    public function unsetAddress(): self
    {
        $this->instance->unsetAddress();
        return $this;
    }

    /**
     * Sets max delivery date field.
     */
    public function maxDeliveryDate(?\DateTime $value): self
    {
        $this->instance->setMaxDeliveryDate($value);
        return $this;
    }

    /**
     * Unsets max delivery date field.
     */
    public function unsetMaxDeliveryDate(): self
    {
        $this->instance->unsetMaxDeliveryDate();
        return $this;
    }

    /**
     * Sets estimated delivery date field.
     */
    public function estimatedDeliveryDate(?\DateTime $value): self
    {
        $this->instance->setEstimatedDeliveryDate($value);
        return $this;
    }

    /**
     * Unsets estimated delivery date field.
     */
    public function unsetEstimatedDeliveryDate(): self
    {
        $this->instance->unsetEstimatedDeliveryDate();
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Unsets type field.
     */
    public function unsetType(): self
    {
        $this->instance->unsetType();
        return $this;
    }

    /**
     * Initializes a new get shipping response object.
     */
    public function build(): GetShippingResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
