<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetTransfer;
use PagarmeApiSDKLib\Models\GetTransferSourceResponse;
use PagarmeApiSDKLib\Models\GetTransferTargetResponse;

/**
 * Builder for model GetTransfer
 *
 * @see GetTransfer
 */
class GetTransferBuilder
{
    /**
     * @var GetTransfer
     */
    private $instance;

    private function __construct(GetTransfer $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new get transfer Builder object.
     */
    public static function init(
        string $id,
        string $gatewayId,
        int $amount,
        string $status,
        \DateTime $createdAt,
        \DateTime $updatedAt,
        string $type,
        GetTransferSourceResponse $source,
        GetTransferTargetResponse $target
    ): self {
        return new self(
            new GetTransfer($id, $gatewayId, $amount, $status, $createdAt, $updatedAt, $type, $source, $target)
        );
    }

    /**
     * Sets metadata field.
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets fee field.
     */
    public function fee(?int $value): self
    {
        $this->instance->setFee($value);
        return $this;
    }

    /**
     * Sets funding date field.
     */
    public function fundingDate(?\DateTime $value): self
    {
        $this->instance->setFundingDate($value);
        return $this;
    }

    /**
     * Sets funding estimated date field.
     */
    public function fundingEstimatedDate(?\DateTime $value): self
    {
        $this->instance->setFundingEstimatedDate($value);
        return $this;
    }

    /**
     * Initializes a new get transfer object.
     */
    public function build(): GetTransfer
    {
        return CoreHelper::clone($this->instance);
    }
}
