<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\UpdatePricingSchemeRequest;
use PagarmeApiSDKLib\Models\UpdateSubscriptionItemRequest;

/**
 * Builder for model UpdateSubscriptionItemRequest
 *
 * @see UpdateSubscriptionItemRequest
 */
class UpdateSubscriptionItemRequestBuilder
{
    /**
     * @var UpdateSubscriptionItemRequest
     */
    private $instance;

    private function __construct(UpdateSubscriptionItemRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new update subscription item request Builder object.
     */
    public static function init(
        string $description,
        string $status,
        UpdatePricingSchemeRequest $pricingScheme,
        string $name
    ): self {
        return new self(new UpdateSubscriptionItemRequest($description, $status, $pricingScheme, $name));
    }

    /**
     * Sets cycles field.
     */
    public function cycles(?int $value): self
    {
        $this->instance->setCycles($value);
        return $this;
    }

    /**
     * Sets quantity field.
     */
    public function quantity(?int $value): self
    {
        $this->instance->setQuantity($value);
        return $this;
    }

    /**
     * Sets minimum price field.
     */
    public function minimumPrice(?int $value): self
    {
        $this->instance->setMinimumPrice($value);
        return $this;
    }

    /**
     * Initializes a new update subscription item request object.
     */
    public function build(): UpdateSubscriptionItemRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
