<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\UpdateSubscriptionBillingDateRequest;

/**
 * Builder for model UpdateSubscriptionBillingDateRequest
 *
 * @see UpdateSubscriptionBillingDateRequest
 */
class UpdateSubscriptionBillingDateRequestBuilder
{
    /**
     * @var UpdateSubscriptionBillingDateRequest
     */
    private $instance;

    private function __construct(UpdateSubscriptionBillingDateRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new update subscription billing date request Builder object.
     */
    public static function init(\DateTime $nextBillingAt): self
    {
        return new self(new UpdateSubscriptionBillingDateRequest($nextBillingAt));
    }

    /**
     * Initializes a new update subscription billing date request object.
     */
    public function build(): UpdateSubscriptionBillingDateRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
