<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\UpdateOrderItemRequest;

/**
 * Builder for model UpdateOrderItemRequest
 *
 * @see UpdateOrderItemRequest
 */
class UpdateOrderItemRequestBuilder
{
    /**
     * @var UpdateOrderItemRequest
     */
    private $instance;

    private function __construct(UpdateOrderItemRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new update order item request Builder object.
     */
    public static function init(int $amount, string $description, int $quantity, string $category): self
    {
        return new self(new UpdateOrderItemRequest($amount, $description, $quantity, $category));
    }

    /**
     * Initializes a new update order item request object.
     */
    public function build(): UpdateOrderItemRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
