<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

/**
 * Credit card settings for creating a payment link
 */
class CreatePaymentLinkCreditCardSettingsRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $operationType;

    /**
     * @var CreatePaymentLinkInstallmentRequest[]|null
     */
    private $installments;

    /**
     * @var CreatePaymentLinkInstallmentsSetupRequest|null
     */
    private $installmentsSetup;

    /**
     * @param string $operationType
     */
    public function __construct(string $operationType)
    {
        $this->operationType = $operationType;
    }

    /**
     * Returns Operation Type.
     * Operation type (auth_and_capture or auth_only)
     */
    public function getOperationType(): string
    {
        return $this->operationType;
    }

    /**
     * Sets Operation Type.
     * Operation type (auth_and_capture or auth_only)
     *
     * @required
     * @maps operation_type
     */
    public function setOperationType(string $operationType): void
    {
        $this->operationType = $operationType;
    }

    /**
     * Returns Installments.
     * Installment options. At least one of installments or installments_setup must be sent, even for a single payment
     *
     * @return CreatePaymentLinkInstallmentRequest[]|null
     */
    public function getInstallments(): ?array
    {
        return $this->installments;
    }

    /**
     * Sets Installments.
     * Installment options. At least one of installments or installments_setup must be sent, even for a single payment
     *
     * @maps installments
     *
     * @param CreatePaymentLinkInstallmentRequest[]|null $installments
     */
    public function setInstallments(?array $installments): void
    {
        $this->installments = $installments;
    }

    /**
     * Returns Installments Setup.
     * Dynamic installments setup. Cannot be sent with installments
     */
    public function getInstallmentsSetup(): ?CreatePaymentLinkInstallmentsSetupRequest
    {
        return $this->installmentsSetup;
    }

    /**
     * Sets Installments Setup.
     * Dynamic installments setup. Cannot be sent with installments
     *
     * @maps installments_setup
     */
    public function setInstallmentsSetup(?CreatePaymentLinkInstallmentsSetupRequest $installmentsSetup): void
    {
        $this->installmentsSetup = $installmentsSetup;
    }

    /**
     * Converts the CreatePaymentLinkCreditCardSettingsRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CreatePaymentLinkCreditCardSettingsRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreatePaymentLinkCreditCardSettingsRequest',
            [
                'operationType' => $this->operationType,
                'installments' => $this->installments,
                'installmentsSetup' => $this->installmentsSetup
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['operation_type']         = $this->operationType;
        if (isset($this->installments)) {
            $json['installments']       = $this->installments;
        }
        if (isset($this->installmentsSetup)) {
            $json['installments_setup'] = $this->installmentsSetup;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
