<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

/**
 * Dynamic installments setup for a payment link
 */
class CreatePaymentLinkInstallmentsSetupRequest implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $maxInstallments;

    /**
     * @var int|null
     */
    private $amount;

    /**
     * @var string|null
     */
    private $interestType;

    /**
     * @var int|null
     */
    private $interestRate;

    /**
     * @var bool|null
     */
    private $customerFee;

    /**
     * @var int|null
     */
    private $freeInstallments;

    /**
     * @var string|null
     */
    private $brand;

    /**
     * Returns Max Installments.
     * Maximum number of installments
     */
    public function getMaxInstallments(): ?int
    {
        return $this->maxInstallments;
    }

    /**
     * Sets Max Installments.
     * Maximum number of installments
     *
     * @maps max_installments
     */
    public function setMaxInstallments(?int $maxInstallments): void
    {
        $this->maxInstallments = $maxInstallments;
    }

    /**
     * Returns Amount.
     * Total amount, in cents
     */
    public function getAmount(): ?int
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * Total amount, in cents
     *
     * @maps amount
     */
    public function setAmount(?int $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Interest Type.
     * Interest type
     */
    public function getInterestType(): ?string
    {
        return $this->interestType;
    }

    /**
     * Sets Interest Type.
     * Interest type
     *
     * @maps interest_type
     */
    public function setInterestType(?string $interestType): void
    {
        $this->interestType = $interestType;
    }

    /**
     * Returns Interest Rate.
     * Interest rate (percentage)
     */
    public function getInterestRate(): ?int
    {
        return $this->interestRate;
    }

    /**
     * Sets Interest Rate.
     * Interest rate (percentage)
     *
     * @maps interest_rate
     */
    public function setInterestRate(?int $interestRate): void
    {
        $this->interestRate = $interestRate;
    }

    /**
     * Returns Customer Fee.
     * Defines whether fees are charged from the customer
     */
    public function getCustomerFee(): ?bool
    {
        return $this->customerFee;
    }

    /**
     * Sets Customer Fee.
     * Defines whether fees are charged from the customer
     *
     * @maps customer_fee
     */
    public function setCustomerFee(?bool $customerFee): void
    {
        $this->customerFee = $customerFee;
    }

    /**
     * Returns Free Installments.
     * Number of installments without interest
     */
    public function getFreeInstallments(): ?int
    {
        return $this->freeInstallments;
    }

    /**
     * Sets Free Installments.
     * Number of installments without interest
     *
     * @maps free_installments
     */
    public function setFreeInstallments(?int $freeInstallments): void
    {
        $this->freeInstallments = $freeInstallments;
    }

    /**
     * Returns Brand.
     * Card brand used to look up fees
     */
    public function getBrand(): ?string
    {
        return $this->brand;
    }

    /**
     * Sets Brand.
     * Card brand used to look up fees
     *
     * @maps brand
     */
    public function setBrand(?string $brand): void
    {
        $this->brand = $brand;
    }

    /**
     * Converts the CreatePaymentLinkInstallmentsSetupRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CreatePaymentLinkInstallmentsSetupRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreatePaymentLinkInstallmentsSetupRequest',
            [
                'maxInstallments' => $this->maxInstallments,
                'amount' => $this->amount,
                'interestType' => $this->interestType,
                'interestRate' => $this->interestRate,
                'customerFee' => $this->customerFee,
                'freeInstallments' => $this->freeInstallments,
                'brand' => $this->brand
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->maxInstallments)) {
            $json['max_installments']  = $this->maxInstallments;
        }
        if (isset($this->amount)) {
            $json['amount']            = $this->amount;
        }
        if (isset($this->interestType)) {
            $json['interest_type']     = $this->interestType;
        }
        if (isset($this->interestRate)) {
            $json['interest_rate']     = $this->interestRate;
        }
        if (isset($this->customerFee)) {
            $json['customer_fee']      = $this->customerFee;
        }
        if (isset($this->freeInstallments)) {
            $json['free_installments'] = $this->freeInstallments;
        }
        if (isset($this->brand)) {
            $json['brand']             = $this->brand;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
