<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

/**
 * Cart item for creating a payment link
 */
class CreatePaymentLinkCartItemRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $name;

    /**
     * @var int
     */
    private $amount;

    /**
     * @var int
     */
    private $defaultQuantity;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var int|null
     */
    private $shippingCost;

    /**
     * @param string $name
     * @param int $amount
     * @param int $defaultQuantity
     */
    public function __construct(string $name, int $amount, int $defaultQuantity)
    {
        $this->name = $name;
        $this->amount = $amount;
        $this->defaultQuantity = $defaultQuantity;
    }

    /**
     * Returns Name.
     * Item name
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Item name
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Amount.
     * Unit amount, in cents
     */
    public function getAmount(): int
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * Unit amount, in cents
     *
     * @required
     * @maps amount
     */
    public function setAmount(int $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Default Quantity.
     * Item quantity
     */
    public function getDefaultQuantity(): int
    {
        return $this->defaultQuantity;
    }

    /**
     * Sets Default Quantity.
     * Item quantity
     *
     * @required
     * @maps default_quantity
     */
    public function setDefaultQuantity(int $defaultQuantity): void
    {
        $this->defaultQuantity = $defaultQuantity;
    }

    /**
     * Returns Description.
     * Item description
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Item description
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Shipping Cost.
     * Item shipping cost, in cents
     */
    public function getShippingCost(): ?int
    {
        return $this->shippingCost;
    }

    /**
     * Sets Shipping Cost.
     * Item shipping cost, in cents
     *
     * @maps shipping_cost
     */
    public function setShippingCost(?int $shippingCost): void
    {
        $this->shippingCost = $shippingCost;
    }

    /**
     * Converts the CreatePaymentLinkCartItemRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CreatePaymentLinkCartItemRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreatePaymentLinkCartItemRequest',
            [
                'name' => $this->name,
                'amount' => $this->amount,
                'defaultQuantity' => $this->defaultQuantity,
                'description' => $this->description,
                'shippingCost' => $this->shippingCost
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['name']              = $this->name;
        $json['amount']            = $this->amount;
        $json['default_quantity']  = $this->defaultQuantity;
        if (isset($this->description)) {
            $json['description']   = $this->description;
        }
        if (isset($this->shippingCost)) {
            $json['shipping_cost'] = $this->shippingCost;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
