<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use stdClass;

/**
 * Request for creating an order item
 */
class CreateOrderItemRequest implements \JsonSerializable
{
    /**
     * @var int
     */
    private $amount;

    /**
     * @var string
     */
    private $description;

    /**
     * @var int
     */
    private $quantity;

    /**
     * @var CreateSellerRequest|null
     */
    private $seller;

    /**
     * @var string|null
     */
    private $sellerId;

    /**
     * @var string
     */
    private $category;

    /**
     * @var string|null
     */
    private $code;

    /**
     * @param int $amount
     * @param string $description
     * @param int $quantity
     * @param string $category
     */
    public function __construct(int $amount, string $description, int $quantity, string $category)
    {
        $this->amount = $amount;
        $this->description = $description;
        $this->quantity = $quantity;
        $this->category = $category;
    }

    /**
     * Returns Amount.
     *
     * Amount
     */
    public function getAmount(): int
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * Amount
     *
     * @required
     * @maps amount
     */
    public function setAmount(int $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Description.
     *
     * Description
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * Description
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Quantity.
     *
     * Quantity
     */
    public function getQuantity(): int
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     *
     * Quantity
     *
     * @required
     * @maps quantity
     */
    public function setQuantity(int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Returns Seller.
     *
     * Item seller
     */
    public function getSeller(): ?CreateSellerRequest
    {
        return $this->seller;
    }

    /**
     * Sets Seller.
     *
     * Item seller
     *
     * @maps seller
     */
    public function setSeller(?CreateSellerRequest $seller): void
    {
        $this->seller = $seller;
    }

    /**
     * Returns Seller Id.
     *
     * seller identificator
     */
    public function getSellerId(): ?string
    {
        return $this->sellerId;
    }

    /**
     * Sets Seller Id.
     *
     * seller identificator
     *
     * @maps seller_id
     */
    public function setSellerId(?string $sellerId): void
    {
        $this->sellerId = $sellerId;
    }

    /**
     * Returns Category.
     *
     * Category
     */
    public function getCategory(): string
    {
        return $this->category;
    }

    /**
     * Sets Category.
     *
     * Category
     *
     * @required
     * @maps category
     */
    public function setCategory(string $category): void
    {
        $this->category = $category;
    }

    /**
     * Returns Code.
     *
     * The item code passed by the client
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * Sets Code.
     *
     * The item code passed by the client
     *
     * @maps code
     */
    public function setCode(?string $code): void
    {
        $this->code = $code;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return mixed
     */
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['amount']        = $this->amount;
        $json['description']   = $this->description;
        $json['quantity']      = $this->quantity;
        if (isset($this->seller)) {
            $json['seller']    = $this->seller;
        }
        if (isset($this->sellerId)) {
            $json['seller_id'] = $this->sellerId;
        }
        $json['category']      = $this->category;
        if (isset($this->code)) {
            $json['code']      = $this->code;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
