<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

/**
 * Cart settings for creating a payment link
 */
class CreatePaymentLinkCartSettingsRequest implements \JsonSerializable
{
    /**
     * @var CreatePaymentLinkCartItemRequest[]|null
     */
    private $items;

    /**
     * @var int|null
     */
    private $shippingCost;

    /**
     * Returns Items.
     * Cart items
     *
     * @return CreatePaymentLinkCartItemRequest[]|null
     */
    public function getItems(): ?array
    {
        return $this->items;
    }

    /**
     * Sets Items.
     * Cart items
     *
     * @maps items
     *
     * @param CreatePaymentLinkCartItemRequest[]|null $items
     */
    public function setItems(?array $items): void
    {
        $this->items = $items;
    }

    /**
     * Returns Shipping Cost.
     * Shipping cost, in cents
     */
    public function getShippingCost(): ?int
    {
        return $this->shippingCost;
    }

    /**
     * Sets Shipping Cost.
     * Shipping cost, in cents
     *
     * @maps shipping_cost
     */
    public function setShippingCost(?int $shippingCost): void
    {
        $this->shippingCost = $shippingCost;
    }

    /**
     * Converts the CreatePaymentLinkCartSettingsRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CreatePaymentLinkCartSettingsRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreatePaymentLinkCartSettingsRequest',
            [
                'items' => $this->items,
                'shippingCost' => $this->shippingCost
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->items)) {
            $json['items']         = $this->items;
        }
        if (isset($this->shippingCost)) {
            $json['shipping_cost'] = $this->shippingCost;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
