<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

/**
 * Payment settings for creating a payment link
 */
class CreatePaymentLinkPaymentSettingsRequest implements \JsonSerializable
{
    /**
     * @var string[]
     */
    private $acceptedPaymentMethods;

    /**
     * @var string|null
     */
    private $statementDescriptor;

    /**
     * @var CreatePaymentLinkCreditCardSettingsRequest|null
     */
    private $creditCardSettings;

    /**
     * @param string[] $acceptedPaymentMethods
     */
    public function __construct(array $acceptedPaymentMethods)
    {
        $this->acceptedPaymentMethods = $acceptedPaymentMethods;
    }

    /**
     * Returns Accepted Payment Methods.
     * Accepted payment methods (credit_card, boleto, pix)
     *
     * @return string[]
     */
    public function getAcceptedPaymentMethods(): array
    {
        return $this->acceptedPaymentMethods;
    }

    /**
     * Sets Accepted Payment Methods.
     * Accepted payment methods (credit_card, boleto, pix)
     *
     * @required
     * @maps accepted_payment_methods
     *
     * @param string[] $acceptedPaymentMethods
     */
    public function setAcceptedPaymentMethods(array $acceptedPaymentMethods): void
    {
        $this->acceptedPaymentMethods = $acceptedPaymentMethods;
    }

    /**
     * Returns Statement Descriptor.
     * Text shown on the card statement
     */
    public function getStatementDescriptor(): ?string
    {
        return $this->statementDescriptor;
    }

    /**
     * Sets Statement Descriptor.
     * Text shown on the card statement
     *
     * @maps statement_descriptor
     */
    public function setStatementDescriptor(?string $statementDescriptor): void
    {
        $this->statementDescriptor = $statementDescriptor;
    }

    /**
     * Returns Credit Card Settings.
     * Credit card settings. Required when credit_card is an accepted payment method
     */
    public function getCreditCardSettings(): ?CreatePaymentLinkCreditCardSettingsRequest
    {
        return $this->creditCardSettings;
    }

    /**
     * Sets Credit Card Settings.
     * Credit card settings. Required when credit_card is an accepted payment method
     *
     * @maps credit_card_settings
     */
    public function setCreditCardSettings(?CreatePaymentLinkCreditCardSettingsRequest $creditCardSettings): void
    {
        $this->creditCardSettings = $creditCardSettings;
    }

    /**
     * Converts the CreatePaymentLinkPaymentSettingsRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CreatePaymentLinkPaymentSettingsRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreatePaymentLinkPaymentSettingsRequest',
            [
                'acceptedPaymentMethods' => $this->acceptedPaymentMethods,
                'statementDescriptor' => $this->statementDescriptor,
                'creditCardSettings' => $this->creditCardSettings
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['accepted_payment_methods'] = $this->acceptedPaymentMethods;
        if (isset($this->statementDescriptor)) {
            $json['statement_descriptor'] = $this->statementDescriptor;
        }
        if (isset($this->creditCardSettings)) {
            $json['credit_card_settings'] = $this->creditCardSettings;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
