<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

/**
 * Paggin response by foward cursor model (Pagging by foward cursor (https://docs.pagar.
 * me/reference/pagina%C3%A7%C3%A3o-1#forward-cursor)
 */
class CursorPagingResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $forwardCursor = 'null';

    /**
     * Returns Forward Cursor.
     * Pagging by foward cursor (https://docs.pagar.me/reference/pagina%C3%A7%C3%A3o-1#forward-cursor)
     */
    public function getForwardCursor(): ?string
    {
        return $this->forwardCursor;
    }

    /**
     * Sets Forward Cursor.
     * Pagging by foward cursor (https://docs.pagar.me/reference/pagina%C3%A7%C3%A3o-1#forward-cursor)
     *
     * @maps forward_cursor
     */
    public function setForwardCursor(?string $forwardCursor): void
    {
        $this->forwardCursor = $forwardCursor;
    }

    /**
     * Converts the CursorPagingResponse object to a human-readable string representation.
     *
     * @return string The string representation of the CursorPagingResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('CursorPagingResponse', ['forwardCursor' => $this->forwardCursor]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['forward_cursor'] = $this->forwardCursor;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
