<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Response object for getting a boleto transaction
 */
class GetBoletoTransactionResponse extends GetTransactionResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $url;

    /**
     * @var string|null
     */
    private $barcode;

    /**
     * @var string|null
     */
    private $nossoNumero;

    /**
     * @var string|null
     */
    private $bank;

    /**
     * @var string|null
     */
    private $documentNumber;

    /**
     * @var string|null
     */
    private $instructions;

    /**
     * @var GetBillingAddressResponse|null
     */
    private $billingAddress;

    /**
     * @var array
     */
    private $dueAt = [];

    /**
     * @var string|null
     */
    private $qrCode;

    /**
     * @var string|null
     */
    private $line;

    /**
     * @var string|null
     */
    private $pdfPassword;

    /**
     * @var string|null
     */
    private $pdf;

    /**
     * @var array
     */
    private $paidAt = [];

    /**
     * @var string|null
     */
    private $paidAmount;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var array
     */
    private $creditAt = [];

    /**
     * @var string|null
     */
    private $statementDescriptor;

    /**
     * Returns Url.
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }

    /**
     * Returns Barcode.
     */
    public function getBarcode(): ?string
    {
        return $this->barcode;
    }

    /**
     * Sets Barcode.
     *
     * @maps barcode
     */
    public function setBarcode(?string $barcode): void
    {
        $this->barcode = $barcode;
    }

    /**
     * Returns Nosso Numero.
     */
    public function getNossoNumero(): ?string
    {
        return $this->nossoNumero;
    }

    /**
     * Sets Nosso Numero.
     *
     * @maps nosso_numero
     */
    public function setNossoNumero(?string $nossoNumero): void
    {
        $this->nossoNumero = $nossoNumero;
    }

    /**
     * Returns Bank.
     */
    public function getBank(): ?string
    {
        return $this->bank;
    }

    /**
     * Sets Bank.
     *
     * @maps bank
     */
    public function setBank(?string $bank): void
    {
        $this->bank = $bank;
    }

    /**
     * Returns Document Number.
     */
    public function getDocumentNumber(): ?string
    {
        return $this->documentNumber;
    }

    /**
     * Sets Document Number.
     *
     * @maps document_number
     */
    public function setDocumentNumber(?string $documentNumber): void
    {
        $this->documentNumber = $documentNumber;
    }

    /**
     * Returns Instructions.
     */
    public function getInstructions(): ?string
    {
        return $this->instructions;
    }

    /**
     * Sets Instructions.
     *
     * @maps instructions
     */
    public function setInstructions(?string $instructions): void
    {
        $this->instructions = $instructions;
    }

    /**
     * Returns Billing Address.
     */
    public function getBillingAddress(): ?GetBillingAddressResponse
    {
        return $this->billingAddress;
    }

    /**
     * Sets Billing Address.
     *
     * @maps billing_address
     */
    public function setBillingAddress(?GetBillingAddressResponse $billingAddress): void
    {
        $this->billingAddress = $billingAddress;
    }

    /**
     * Returns Due At.
     */
    public function getDueAt(): ?\DateTime
    {
        if (count($this->dueAt) == 0) {
            return null;
        }
        return $this->dueAt['value'];
    }

    /**
     * Sets Due At.
     *
     * @maps due_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDueAt(?\DateTime $dueAt): void
    {
        $this->dueAt['value'] = $dueAt;
    }

    /**
     * Unsets Due At.
     */
    public function unsetDueAt(): void
    {
        $this->dueAt = [];
    }

    /**
     * Returns Qr Code.
     */
    public function getQrCode(): ?string
    {
        return $this->qrCode;
    }

    /**
     * Sets Qr Code.
     *
     * @maps qr_code
     */
    public function setQrCode(?string $qrCode): void
    {
        $this->qrCode = $qrCode;
    }

    /**
     * Returns Line.
     */
    public function getLine(): ?string
    {
        return $this->line;
    }

    /**
     * Sets Line.
     *
     * @maps line
     */
    public function setLine(?string $line): void
    {
        $this->line = $line;
    }

    /**
     * Returns Pdf Password.
     */
    public function getPdfPassword(): ?string
    {
        return $this->pdfPassword;
    }

    /**
     * Sets Pdf Password.
     *
     * @maps pdf_password
     */
    public function setPdfPassword(?string $pdfPassword): void
    {
        $this->pdfPassword = $pdfPassword;
    }

    /**
     * Returns Pdf.
     */
    public function getPdf(): ?string
    {
        return $this->pdf;
    }

    /**
     * Sets Pdf.
     *
     * @maps pdf
     */
    public function setPdf(?string $pdf): void
    {
        $this->pdf = $pdf;
    }

    /**
     * Returns Paid At.
     */
    public function getPaidAt(): ?\DateTime
    {
        if (count($this->paidAt) == 0) {
            return null;
        }
        return $this->paidAt['value'];
    }

    /**
     * Sets Paid At.
     *
     * @maps paid_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setPaidAt(?\DateTime $paidAt): void
    {
        $this->paidAt['value'] = $paidAt;
    }

    /**
     * Unsets Paid At.
     */
    public function unsetPaidAt(): void
    {
        $this->paidAt = [];
    }

    /**
     * Returns Paid Amount.
     */
    public function getPaidAmount(): ?string
    {
        return $this->paidAmount;
    }

    /**
     * Sets Paid Amount.
     *
     * @maps paid_amount
     */
    public function setPaidAmount(?string $paidAmount): void
    {
        $this->paidAmount = $paidAmount;
    }

    /**
     * Returns Type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Credit At.
     */
    public function getCreditAt(): ?\DateTime
    {
        if (count($this->creditAt) == 0) {
            return null;
        }
        return $this->creditAt['value'];
    }

    /**
     * Sets Credit At.
     *
     * @maps credit_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreditAt(?\DateTime $creditAt): void
    {
        $this->creditAt['value'] = $creditAt;
    }

    /**
     * Unsets Credit At.
     */
    public function unsetCreditAt(): void
    {
        $this->creditAt = [];
    }

    /**
     * Returns Statement Descriptor.
     * Soft Descriptor
     */
    public function getStatementDescriptor(): ?string
    {
        return $this->statementDescriptor;
    }

    /**
     * Sets Statement Descriptor.
     * Soft Descriptor
     *
     * @maps statement_descriptor
     */
    public function setStatementDescriptor(?string $statementDescriptor): void
    {
        $this->statementDescriptor = $statementDescriptor;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['url']                  = $this->url;
        $json['barcode']              = $this->barcode;
        $json['nosso_numero']         = $this->nossoNumero;
        $json['bank']                 = $this->bank;
        $json['document_number']      = $this->documentNumber;
        $json['instructions']         = $this->instructions;
        $json['billing_address']      = $this->billingAddress;
        if (!empty($this->dueAt)) {
            $json['due_at']           = DateTimeHelper::toRfc3339DateTime($this->dueAt['value']);
        }
        $json['qr_code']              = $this->qrCode;
        $json['line']                 = $this->line;
        $json['pdf_password']         = $this->pdfPassword;
        $json['pdf']                  = $this->pdf;
        if (!empty($this->paidAt)) {
            $json['paid_at']          = DateTimeHelper::toRfc3339DateTime($this->paidAt['value']);
        }
        $json['paid_amount']          = $this->paidAmount;
        $json['type']                 = $this->type;
        if (!empty($this->creditAt)) {
            $json['credit_at']        = DateTimeHelper::toRfc3339DateTime($this->creditAt['value']);
        }
        $json['statement_descriptor'] = $this->statementDescriptor;
        $json = array_merge($json, parent::jsonSerialize(true));

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
