<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Checkout pix payment response
 */
class GetCheckoutPixPaymentResponse implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $expiresAt;

    /**
     * @var PixAdditionalInformation[]|null
     */
    private $additionalInformation;

    /**
     * Returns Expires At.
     * Expires at
     */
    public function getExpiresAt(): ?\DateTime
    {
        return $this->expiresAt;
    }

    /**
     * Sets Expires At.
     * Expires at
     *
     * @maps expires_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setExpiresAt(?\DateTime $expiresAt): void
    {
        $this->expiresAt = $expiresAt;
    }

    /**
     * Returns Additional Information.
     * Additional information
     *
     * @return PixAdditionalInformation[]|null
     */
    public function getAdditionalInformation(): ?array
    {
        return $this->additionalInformation;
    }

    /**
     * Sets Additional Information.
     * Additional information
     *
     * @maps additional_information
     *
     * @param PixAdditionalInformation[]|null $additionalInformation
     */
    public function setAdditionalInformation(?array $additionalInformation): void
    {
        $this->additionalInformation = $additionalInformation;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['expires_at']             = DateTimeHelper::toRfc3339DateTime($this->expiresAt);
        $json['additional_information'] = $this->additionalInformation;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
