<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use stdClass;

class GetChargesSummaryResponse implements \JsonSerializable
{
    /**
     * @var array
     */
    private $total = [];

    /**
     * Returns Total.
     */
    public function getTotal(): ?int
    {
        if (count($this->total) == 0) {
            return null;
        }
        return $this->total['value'];
    }

    /**
     * Sets Total.
     *
     * @maps total
     */
    public function setTotal(?int $total): void
    {
        $this->total['value'] = $total;
    }

    /**
     * Unsets Total.
     */
    public function unsetTotal(): void
    {
        $this->total = [];
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->total)) {
            $json['total'] = $this->total['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
