<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use stdClass;

/**
 * Information about the recipient on the gateway
 */
class GetGatewayRecipientResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $gateway;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $pgid;

    /**
     * @var string|null
     */
    private $createdAt;

    /**
     * @var string|null
     */
    private $updatedAt;

    /**
     * Returns Gateway.
     * Gateway name
     */
    public function getGateway(): ?string
    {
        return $this->gateway;
    }

    /**
     * Sets Gateway.
     * Gateway name
     *
     * @maps gateway
     */
    public function setGateway(?string $gateway): void
    {
        $this->gateway = $gateway;
    }

    /**
     * Returns Status.
     * Status of the recipient on the gateway
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * Status of the recipient on the gateway
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Pgid.
     * Recipient id on the gateway
     */
    public function getPgid(): ?string
    {
        return $this->pgid;
    }

    /**
     * Sets Pgid.
     * Recipient id on the gateway
     *
     * @maps pgid
     */
    public function setPgid(?string $pgid): void
    {
        $this->pgid = $pgid;
    }

    /**
     * Returns Created At.
     * Creation date
     */
    public function getCreatedAt(): ?string
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     * Creation date
     *
     * @maps created_at
     */
    public function setCreatedAt(?string $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Updated At.
     * Last update date
     */
    public function getUpdatedAt(): ?string
    {
        return $this->updatedAt;
    }

    /**
     * Sets Updated At.
     * Last update date
     *
     * @maps updated_at
     */
    public function setUpdatedAt(?string $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['gateway']    = $this->gateway;
        $json['status']     = $this->status;
        $json['pgid']       = $this->pgid;
        $json['created_at'] = $this->createdAt;
        $json['updated_at'] = $this->updatedAt;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
