<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use stdClass;

/**
 * Response object for getting an invoice item
 */
class GetInvoiceItemResponse implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $amount;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var GetPricingSchemeResponse|null
     */
    private $pricingScheme;

    /**
     * @var GetPriceBracketResponse|null
     */
    private $priceBracket;

    /**
     * @var array
     */
    private $quantity = [];

    /**
     * @var array
     */
    private $name = [];

    /**
     * @var string|null
     */
    private $subscriptionItemId;

    /**
     * Returns Amount.
     */
    public function getAmount(): ?int
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @maps amount
     */
    public function setAmount(?int $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Pricing Scheme.
     */
    public function getPricingScheme(): ?GetPricingSchemeResponse
    {
        return $this->pricingScheme;
    }

    /**
     * Sets Pricing Scheme.
     *
     * @maps pricing_scheme
     */
    public function setPricingScheme(?GetPricingSchemeResponse $pricingScheme): void
    {
        $this->pricingScheme = $pricingScheme;
    }

    /**
     * Returns Price Bracket.
     */
    public function getPriceBracket(): ?GetPriceBracketResponse
    {
        return $this->priceBracket;
    }

    /**
     * Sets Price Bracket.
     *
     * @maps price_bracket
     */
    public function setPriceBracket(?GetPriceBracketResponse $priceBracket): void
    {
        $this->priceBracket = $priceBracket;
    }

    /**
     * Returns Quantity.
     */
    public function getQuantity(): ?int
    {
        if (count($this->quantity) == 0) {
            return null;
        }
        return $this->quantity['value'];
    }

    /**
     * Sets Quantity.
     *
     * @maps quantity
     */
    public function setQuantity(?int $quantity): void
    {
        $this->quantity['value'] = $quantity;
    }

    /**
     * Unsets Quantity.
     */
    public function unsetQuantity(): void
    {
        $this->quantity = [];
    }

    /**
     * Returns Name.
     */
    public function getName(): ?string
    {
        if (count($this->name) == 0) {
            return null;
        }
        return $this->name['value'];
    }

    /**
     * Sets Name.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name['value'] = $name;
    }

    /**
     * Unsets Name.
     */
    public function unsetName(): void
    {
        $this->name = [];
    }

    /**
     * Returns Subscription Item Id.
     * Subscription Item Id
     */
    public function getSubscriptionItemId(): ?string
    {
        return $this->subscriptionItemId;
    }

    /**
     * Sets Subscription Item Id.
     * Subscription Item Id
     *
     * @maps subscription_item_id
     */
    public function setSubscriptionItemId(?string $subscriptionItemId): void
    {
        $this->subscriptionItemId = $subscriptionItemId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['amount']               = $this->amount;
        $json['description']          = $this->description;
        $json['pricing_scheme']       = $this->pricingScheme;
        $json['price_bracket']        = $this->priceBracket;
        if (!empty($this->quantity)) {
            $json['quantity']         = $this->quantity['value'];
        }
        if (!empty($this->name)) {
            $json['name']             = $this->name['value'];
        }
        $json['subscription_item_id'] = $this->subscriptionItemId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
