<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Response object for getting an invoice
 */
class GetInvoiceResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $code;

    /**
     * @var string|null
     */
    private $url;

    /**
     * @var int|null
     */
    private $amount;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $paymentMethod;

    /**
     * @var \DateTime|null
     */
    private $createdAt;

    /**
     * @var GetInvoiceItemResponse[]|null
     */
    private $items;

    /**
     * @var array
     */
    private $customer = [];

    /**
     * @var GetChargeResponse|null
     */
    private $charge;

    /**
     * @var int|null
     */
    private $installments;

    /**
     * @var GetBillingAddressResponse|null
     */
    private $billingAddress;

    /**
     * @var GetSubscriptionResponse|null
     */
    private $subscription;

    /**
     * @var array
     */
    private $cycle = [];

    /**
     * @var GetShippingResponse|null
     */
    private $shipping;

    /**
     * @var array<string,string>|null
     */
    private $metadata;

    /**
     * @var array
     */
    private $dueAt = [];

    /**
     * @var array
     */
    private $canceledAt = [];

    /**
     * @var array
     */
    private $billingAt = [];

    /**
     * @var array
     */
    private $seenAt = [];

    /**
     * @var array
     */
    private $totalDiscount = [];

    /**
     * @var array
     */
    private $totalIncrement = [];

    /**
     * @var string|null
     */
    private $subscriptionId;

    /**
     * Returns Id.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Code.
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * Sets Code.
     *
     * @maps code
     */
    public function setCode(?string $code): void
    {
        $this->code = $code;
    }

    /**
     * Returns Url.
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }

    /**
     * Returns Amount.
     */
    public function getAmount(): ?int
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @maps amount
     */
    public function setAmount(?int $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Payment Method.
     */
    public function getPaymentMethod(): ?string
    {
        return $this->paymentMethod;
    }

    /**
     * Sets Payment Method.
     *
     * @maps payment_method
     */
    public function setPaymentMethod(?string $paymentMethod): void
    {
        $this->paymentMethod = $paymentMethod;
    }

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     *
     * @maps created_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(?\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Items.
     *
     * @return GetInvoiceItemResponse[]|null
     */
    public function getItems(): ?array
    {
        return $this->items;
    }

    /**
     * Sets Items.
     *
     * @maps items
     *
     * @param GetInvoiceItemResponse[]|null $items
     */
    public function setItems(?array $items): void
    {
        $this->items = $items;
    }

    /**
     * Returns Customer.
     */
    public function getCustomer(): ?GetCustomerResponse
    {
        if (count($this->customer) == 0) {
            return null;
        }
        return $this->customer['value'];
    }

    /**
     * Sets Customer.
     *
     * @maps customer
     */
    public function setCustomer(?GetCustomerResponse $customer): void
    {
        $this->customer['value'] = $customer;
    }

    /**
     * Unsets Customer.
     */
    public function unsetCustomer(): void
    {
        $this->customer = [];
    }

    /**
     * Returns Charge.
     */
    public function getCharge(): ?GetChargeResponse
    {
        return $this->charge;
    }

    /**
     * Sets Charge.
     *
     * @maps charge
     */
    public function setCharge(?GetChargeResponse $charge): void
    {
        $this->charge = $charge;
    }

    /**
     * Returns Installments.
     */
    public function getInstallments(): ?int
    {
        return $this->installments;
    }

    /**
     * Sets Installments.
     *
     * @maps installments
     */
    public function setInstallments(?int $installments): void
    {
        $this->installments = $installments;
    }

    /**
     * Returns Billing Address.
     */
    public function getBillingAddress(): ?GetBillingAddressResponse
    {
        return $this->billingAddress;
    }

    /**
     * Sets Billing Address.
     *
     * @maps billing_address
     */
    public function setBillingAddress(?GetBillingAddressResponse $billingAddress): void
    {
        $this->billingAddress = $billingAddress;
    }

    /**
     * Returns Subscription.
     */
    public function getSubscription(): ?GetSubscriptionResponse
    {
        return $this->subscription;
    }

    /**
     * Sets Subscription.
     *
     * @maps subscription
     */
    public function setSubscription(?GetSubscriptionResponse $subscription): void
    {
        $this->subscription = $subscription;
    }

    /**
     * Returns Cycle.
     */
    public function getCycle(): ?GetPeriodResponse
    {
        if (count($this->cycle) == 0) {
            return null;
        }
        return $this->cycle['value'];
    }

    /**
     * Sets Cycle.
     *
     * @maps cycle
     */
    public function setCycle(?GetPeriodResponse $cycle): void
    {
        $this->cycle['value'] = $cycle;
    }

    /**
     * Unsets Cycle.
     */
    public function unsetCycle(): void
    {
        $this->cycle = [];
    }

    /**
     * Returns Shipping.
     */
    public function getShipping(): ?GetShippingResponse
    {
        return $this->shipping;
    }

    /**
     * Sets Shipping.
     *
     * @maps shipping
     */
    public function setShipping(?GetShippingResponse $shipping): void
    {
        $this->shipping = $shipping;
    }

    /**
     * Returns Metadata.
     *
     * @return array<string,string>|null
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     *
     * @maps metadata
     *
     * @param array<string,string>|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Returns Due At.
     */
    public function getDueAt(): ?\DateTime
    {
        if (count($this->dueAt) == 0) {
            return null;
        }
        return $this->dueAt['value'];
    }

    /**
     * Sets Due At.
     *
     * @maps due_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDueAt(?\DateTime $dueAt): void
    {
        $this->dueAt['value'] = $dueAt;
    }

    /**
     * Unsets Due At.
     */
    public function unsetDueAt(): void
    {
        $this->dueAt = [];
    }

    /**
     * Returns Canceled At.
     */
    public function getCanceledAt(): ?\DateTime
    {
        if (count($this->canceledAt) == 0) {
            return null;
        }
        return $this->canceledAt['value'];
    }

    /**
     * Sets Canceled At.
     *
     * @maps canceled_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCanceledAt(?\DateTime $canceledAt): void
    {
        $this->canceledAt['value'] = $canceledAt;
    }

    /**
     * Unsets Canceled At.
     */
    public function unsetCanceledAt(): void
    {
        $this->canceledAt = [];
    }

    /**
     * Returns Billing At.
     */
    public function getBillingAt(): ?\DateTime
    {
        if (count($this->billingAt) == 0) {
            return null;
        }
        return $this->billingAt['value'];
    }

    /**
     * Sets Billing At.
     *
     * @maps billing_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setBillingAt(?\DateTime $billingAt): void
    {
        $this->billingAt['value'] = $billingAt;
    }

    /**
     * Unsets Billing At.
     */
    public function unsetBillingAt(): void
    {
        $this->billingAt = [];
    }

    /**
     * Returns Seen At.
     */
    public function getSeenAt(): ?\DateTime
    {
        if (count($this->seenAt) == 0) {
            return null;
        }
        return $this->seenAt['value'];
    }

    /**
     * Sets Seen At.
     *
     * @maps seen_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setSeenAt(?\DateTime $seenAt): void
    {
        $this->seenAt['value'] = $seenAt;
    }

    /**
     * Unsets Seen At.
     */
    public function unsetSeenAt(): void
    {
        $this->seenAt = [];
    }

    /**
     * Returns Total Discount.
     * Total discounted value
     */
    public function getTotalDiscount(): ?int
    {
        if (count($this->totalDiscount) == 0) {
            return null;
        }
        return $this->totalDiscount['value'];
    }

    /**
     * Sets Total Discount.
     * Total discounted value
     *
     * @maps total_discount
     */
    public function setTotalDiscount(?int $totalDiscount): void
    {
        $this->totalDiscount['value'] = $totalDiscount;
    }

    /**
     * Unsets Total Discount.
     * Total discounted value
     */
    public function unsetTotalDiscount(): void
    {
        $this->totalDiscount = [];
    }

    /**
     * Returns Total Increment.
     * Total discounted value
     */
    public function getTotalIncrement(): ?int
    {
        if (count($this->totalIncrement) == 0) {
            return null;
        }
        return $this->totalIncrement['value'];
    }

    /**
     * Sets Total Increment.
     * Total discounted value
     *
     * @maps total_increment
     */
    public function setTotalIncrement(?int $totalIncrement): void
    {
        $this->totalIncrement['value'] = $totalIncrement;
    }

    /**
     * Unsets Total Increment.
     * Total discounted value
     */
    public function unsetTotalIncrement(): void
    {
        $this->totalIncrement = [];
    }

    /**
     * Returns Subscription Id.
     * Subscription Id
     */
    public function getSubscriptionId(): ?string
    {
        return $this->subscriptionId;
    }

    /**
     * Sets Subscription Id.
     * Subscription Id
     *
     * @maps subscription_id
     */
    public function setSubscriptionId(?string $subscriptionId): void
    {
        $this->subscriptionId = $subscriptionId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']                  = $this->id;
        $json['code']                = $this->code;
        $json['url']                 = $this->url;
        $json['amount']              = $this->amount;
        $json['status']              = $this->status;
        $json['payment_method']      = $this->paymentMethod;
        $json['created_at']          = DateTimeHelper::toRfc3339DateTime($this->createdAt);
        $json['items']               = $this->items;
        if (!empty($this->customer)) {
            $json['customer']        = $this->customer['value'];
        }
        $json['charge']              = $this->charge;
        $json['installments']        = $this->installments;
        $json['billing_address']     = $this->billingAddress;
        $json['subscription']        = $this->subscription;
        if (!empty($this->cycle)) {
            $json['cycle']           = $this->cycle['value'];
        }
        $json['shipping']            = $this->shipping;
        $json['metadata']            = $this->metadata;
        if (!empty($this->dueAt)) {
            $json['due_at']          = DateTimeHelper::toRfc3339DateTime($this->dueAt['value']);
        }
        if (!empty($this->canceledAt)) {
            $json['canceled_at']     = DateTimeHelper::toRfc3339DateTime($this->canceledAt['value']);
        }
        if (!empty($this->billingAt)) {
            $json['billing_at']      = DateTimeHelper::toRfc3339DateTime($this->billingAt['value']);
        }
        if (!empty($this->seenAt)) {
            $json['seen_at']         = DateTimeHelper::toRfc3339DateTime($this->seenAt['value']);
        }
        if (!empty($this->totalDiscount)) {
            $json['total_discount']  = $this->totalDiscount['value'];
        }
        if (!empty($this->totalIncrement)) {
            $json['total_increment'] = $this->totalIncrement['value'];
        }
        $json['subscription_id']     = $this->subscriptionId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
