<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use PagarmeApiSDKLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Response object for getting an payable
 */
class GetPayableResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $status;

    /**
     * @var int
     */
    private $amount;

    /**
     * @var array
     */
    private $fee = [];

    /**
     * @var array
     */
    private $anticipationFee = [];

    /**
     * @var array
     */
    private $fraudCoverageFee = [];

    /**
     * @var array
     */
    private $installment = [];

    /**
     * @var string|null
     */
    private $gatewayId = 'null';

    /**
     * @var string|null
     */
    private $chargeId = 'null';

    /**
     * @var string|null
     */
    private $splitId = 'null';

    /**
     * @var string|null
     */
    private $bulkAnticipationId = 'null';

    /**
     * @var array
     */
    private $anticipationId = [];

    /**
     * @var string|null
     */
    private $recipientId;

    /**
     * @var string|null
     */
    private $originatorModel = 'null';

    /**
     * @var string|null
     */
    private $originatorModelId = 'null';

    /**
     * @var array
     */
    private $paymentDate = [];

    /**
     * @var \DateTime|null
     */
    private $originalPaymentDate;

    /**
     * @var array
     */
    private $type = [];

    /**
     * @var string|null
     */
    private $paymentMethod = 'null';

    /**
     * @var array
     */
    private $accrualAt = [];

    /**
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @var array
     */
    private $liquidationArrangementId = ['value' => 'null'];

    /**
     * @var string|null
     */
    private $settlementId = 'null';

    /**
     * @var string|null
     */
    private $paymentProfileId = 'null';

    /**
     * @param string $id
     * @param string $status
     * @param int $amount
     * @param \DateTime $createdAt
     */
    public function __construct(string $id, string $status, int $amount, \DateTime $createdAt)
    {
        $this->id = $id;
        $this->status = $status;
        $this->amount = $amount;
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Id.
     * Payable Identifier
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Payable Identifier
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Status.
     * Payable status
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * Payable status
     *
     * @required
     * @maps status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Amount.
     * Payable amount in cents
     */
    public function getAmount(): int
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * Payable amount in cents
     *
     * @required
     * @maps amount
     */
    public function setAmount(int $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Fee.
     * Payable fee amount in cents
     */
    public function getFee(): ?int
    {
        if (count($this->fee) == 0) {
            return null;
        }
        return $this->fee['value'];
    }

    /**
     * Sets Fee.
     * Payable fee amount in cents
     *
     * @maps fee
     */
    public function setFee(?int $fee): void
    {
        $this->fee['value'] = $fee;
    }

    /**
     * Unsets Fee.
     * Payable fee amount in cents
     */
    public function unsetFee(): void
    {
        $this->fee = [];
    }

    /**
     * Returns Anticipation Fee.
     * Antecipation fee amount in cents
     */
    public function getAnticipationFee(): ?int
    {
        if (count($this->anticipationFee) == 0) {
            return null;
        }
        return $this->anticipationFee['value'];
    }

    /**
     * Sets Anticipation Fee.
     * Antecipation fee amount in cents
     *
     * @maps anticipation_fee
     */
    public function setAnticipationFee(?int $anticipationFee): void
    {
        $this->anticipationFee['value'] = $anticipationFee;
    }

    /**
     * Unsets Anticipation Fee.
     * Antecipation fee amount in cents
     */
    public function unsetAnticipationFee(): void
    {
        $this->anticipationFee = [];
    }

    /**
     * Returns Fraud Coverage Fee.
     * Fraud coverage fee amount in cents
     */
    public function getFraudCoverageFee(): ?int
    {
        if (count($this->fraudCoverageFee) == 0) {
            return null;
        }
        return $this->fraudCoverageFee['value'];
    }

    /**
     * Sets Fraud Coverage Fee.
     * Fraud coverage fee amount in cents
     *
     * @maps fraud_coverage_fee
     */
    public function setFraudCoverageFee(?int $fraudCoverageFee): void
    {
        $this->fraudCoverageFee['value'] = $fraudCoverageFee;
    }

    /**
     * Unsets Fraud Coverage Fee.
     * Fraud coverage fee amount in cents
     */
    public function unsetFraudCoverageFee(): void
    {
        $this->fraudCoverageFee = [];
    }

    /**
     * Returns Installment.
     * Number of installment
     */
    public function getInstallment(): ?int
    {
        if (count($this->installment) == 0) {
            return null;
        }
        return $this->installment['value'];
    }

    /**
     * Sets Installment.
     * Number of installment
     *
     * @maps installment
     */
    public function setInstallment(?int $installment): void
    {
        $this->installment['value'] = $installment;
    }

    /**
     * Unsets Installment.
     * Number of installment
     */
    public function unsetInstallment(): void
    {
        $this->installment = [];
    }

    /**
     * Returns Gateway Id.
     * Payment gateway identifier
     */
    public function getGatewayId(): ?string
    {
        return $this->gatewayId;
    }

    /**
     * Sets Gateway Id.
     * Payment gateway identifier
     *
     * @maps gateway_id
     */
    public function setGatewayId(?string $gatewayId): void
    {
        $this->gatewayId = $gatewayId;
    }

    /**
     * Returns Charge Id.
     * Charge identifier
     */
    public function getChargeId(): ?string
    {
        return $this->chargeId;
    }

    /**
     * Sets Charge Id.
     * Charge identifier
     *
     * @maps charge_id
     */
    public function setChargeId(?string $chargeId): void
    {
        $this->chargeId = $chargeId;
    }

    /**
     * Returns Split Id.
     */
    public function getSplitId(): ?string
    {
        return $this->splitId;
    }

    /**
     * Sets Split Id.
     *
     * @maps split_id
     */
    public function setSplitId(?string $splitId): void
    {
        $this->splitId = $splitId;
    }

    /**
     * Returns Bulk Anticipation Id.
     */
    public function getBulkAnticipationId(): ?string
    {
        return $this->bulkAnticipationId;
    }

    /**
     * Sets Bulk Anticipation Id.
     *
     * @maps bulk_anticipation_id
     */
    public function setBulkAnticipationId(?string $bulkAnticipationId): void
    {
        $this->bulkAnticipationId = $bulkAnticipationId;
    }

    /**
     * Returns Anticipation Id.
     */
    public function getAnticipationId(): ?string
    {
        if (count($this->anticipationId) == 0) {
            return null;
        }
        return $this->anticipationId['value'];
    }

    /**
     * Sets Anticipation Id.
     *
     * @maps anticipation_id
     */
    public function setAnticipationId(?string $anticipationId): void
    {
        $this->anticipationId['value'] = $anticipationId;
    }

    /**
     * Unsets Anticipation Id.
     */
    public function unsetAnticipationId(): void
    {
        $this->anticipationId = [];
    }

    /**
     * Returns Recipient Id.
     * Recipient identifier
     */
    public function getRecipientId(): ?string
    {
        return $this->recipientId;
    }

    /**
     * Sets Recipient Id.
     * Recipient identifier
     *
     * @maps recipient_id
     */
    public function setRecipientId(?string $recipientId): void
    {
        $this->recipientId = $recipientId;
    }

    /**
     * Returns Originator Model.
     */
    public function getOriginatorModel(): ?string
    {
        return $this->originatorModel;
    }

    /**
     * Sets Originator Model.
     *
     * @maps originator_model
     */
    public function setOriginatorModel(?string $originatorModel): void
    {
        $this->originatorModel = $originatorModel;
    }

    /**
     * Returns Originator Model Id.
     * Originator model identifier
     */
    public function getOriginatorModelId(): ?string
    {
        return $this->originatorModelId;
    }

    /**
     * Sets Originator Model Id.
     * Originator model identifier
     *
     * @maps originator_model_id
     */
    public function setOriginatorModelId(?string $originatorModelId): void
    {
        $this->originatorModelId = $originatorModelId;
    }

    /**
     * Returns Payment Date.
     * Payment Date
     */
    public function getPaymentDate(): ?\DateTime
    {
        if (count($this->paymentDate) == 0) {
            return null;
        }
        return $this->paymentDate['value'];
    }

    /**
     * Sets Payment Date.
     * Payment Date
     *
     * @maps payment_date
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setPaymentDate(?\DateTime $paymentDate): void
    {
        $this->paymentDate['value'] = $paymentDate;
    }

    /**
     * Unsets Payment Date.
     * Payment Date
     */
    public function unsetPaymentDate(): void
    {
        $this->paymentDate = [];
    }

    /**
     * Returns Original Payment Date.
     * Original Payment Date
     */
    public function getOriginalPaymentDate(): ?\DateTime
    {
        return $this->originalPaymentDate;
    }

    /**
     * Sets Original Payment Date.
     * Original Payment Date
     *
     * @maps original_payment_date
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setOriginalPaymentDate(?\DateTime $originalPaymentDate): void
    {
        $this->originalPaymentDate = $originalPaymentDate;
    }

    /**
     * Returns Type.
     * Type of payable
     */
    public function getType(): ?string
    {
        if (count($this->type) == 0) {
            return null;
        }
        return $this->type['value'];
    }

    /**
     * Sets Type.
     * Type of payable
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type['value'] = $type;
    }

    /**
     * Unsets Type.
     * Type of payable
     */
    public function unsetType(): void
    {
        $this->type = [];
    }

    /**
     * Returns Payment Method.
     * Payment method of transaction
     */
    public function getPaymentMethod(): ?string
    {
        return $this->paymentMethod;
    }

    /**
     * Sets Payment Method.
     * Payment method of transaction
     *
     * @maps payment_method
     */
    public function setPaymentMethod(?string $paymentMethod): void
    {
        $this->paymentMethod = $paymentMethod;
    }

    /**
     * Returns Accrual At.
     * Date issuer identify payment
     */
    public function getAccrualAt(): ?\DateTime
    {
        if (count($this->accrualAt) == 0) {
            return null;
        }
        return $this->accrualAt['value'];
    }

    /**
     * Sets Accrual At.
     * Date issuer identify payment
     *
     * @maps accrual_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setAccrualAt(?\DateTime $accrualAt): void
    {
        $this->accrualAt['value'] = $accrualAt;
    }

    /**
     * Unsets Accrual At.
     * Date issuer identify payment
     */
    public function unsetAccrualAt(): void
    {
        $this->accrualAt = [];
    }

    /**
     * Returns Created At.
     * Creation date
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     * Creation date
     *
     * @required
     * @maps created_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Liquidation Arrangement Id.
     */
    public function getLiquidationArrangementId(): ?string
    {
        if (count($this->liquidationArrangementId) == 0) {
            return null;
        }
        return $this->liquidationArrangementId['value'];
    }

    /**
     * Sets Liquidation Arrangement Id.
     *
     * @maps liquidation_arrangement_id
     */
    public function setLiquidationArrangementId(?string $liquidationArrangementId): void
    {
        $this->liquidationArrangementId['value'] = $liquidationArrangementId;
    }

    /**
     * Unsets Liquidation Arrangement Id.
     */
    public function unsetLiquidationArrangementId(): void
    {
        $this->liquidationArrangementId = [];
    }

    /**
     * Returns Settlement Id.
     * Settlement identifier  (new in v7.x)
     */
    public function getSettlementId(): ?string
    {
        return $this->settlementId;
    }

    /**
     * Sets Settlement Id.
     * Settlement identifier  (new in v7.x)
     *
     * @maps settlement_id
     */
    public function setSettlementId(?string $settlementId): void
    {
        $this->settlementId = $settlementId;
    }

    /**
     * Returns Payment Profile Id.
     * Operational identifier of merchant inside of payment platform (new in v7.x)
     */
    public function getPaymentProfileId(): ?string
    {
        return $this->paymentProfileId;
    }

    /**
     * Sets Payment Profile Id.
     * Operational identifier of merchant inside of payment platform (new in v7.x)
     *
     * @maps payment_profile_id
     */
    public function setPaymentProfileId(?string $paymentProfileId): void
    {
        $this->paymentProfileId = $paymentProfileId;
    }

    /**
     * Converts the GetPayableResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetPayableResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetPayableResponse',
            [
                'id' => $this->id,
                'status' => $this->status,
                'amount' => $this->amount,
                'fee' => $this->getFee(),
                'anticipationFee' => $this->getAnticipationFee(),
                'fraudCoverageFee' => $this->getFraudCoverageFee(),
                'installment' => $this->getInstallment(),
                'gatewayId' => $this->gatewayId,
                'chargeId' => $this->chargeId,
                'splitId' => $this->splitId,
                'bulkAnticipationId' => $this->bulkAnticipationId,
                'anticipationId' => $this->getAnticipationId(),
                'recipientId' => $this->recipientId,
                'originatorModel' => $this->originatorModel,
                'originatorModelId' => $this->originatorModelId,
                'paymentDate' => $this->getPaymentDate(),
                'originalPaymentDate' => $this->originalPaymentDate,
                'type' => $this->getType(),
                'paymentMethod' => $this->paymentMethod,
                'accrualAt' => $this->getAccrualAt(),
                'createdAt' => $this->createdAt,
                'liquidationArrangementId' => $this->getLiquidationArrangementId(),
                'settlementId' => $this->settlementId,
                'paymentProfileId' => $this->paymentProfileId
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']                             = $this->id;
        $json['status']                         = $this->status;
        $json['amount']                         = $this->amount;
        if (!empty($this->fee)) {
            $json['fee']                        = $this->fee['value'];
        }
        if (!empty($this->anticipationFee)) {
            $json['anticipation_fee']           = $this->anticipationFee['value'];
        }
        if (!empty($this->fraudCoverageFee)) {
            $json['fraud_coverage_fee']         = $this->fraudCoverageFee['value'];
        }
        if (!empty($this->installment)) {
            $json['installment']                = $this->installment['value'];
        }
        $json['gateway_id']                     = $this->gatewayId;
        $json['charge_id']                      = $this->chargeId;
        $json['split_id']                       = $this->splitId;
        $json['bulk_anticipation_id']           = $this->bulkAnticipationId;
        if (!empty($this->anticipationId)) {
            $json['anticipation_id']            = $this->anticipationId['value'];
        }
        $json['recipient_id']                   = $this->recipientId;
        $json['originator_model']               = $this->originatorModel;
        $json['originator_model_id']            = $this->originatorModelId;
        if (!empty($this->paymentDate)) {
            $json['payment_date']               = DateTimeHelper::toRfc3339DateTime($this->paymentDate['value']);
        }
        $json['original_payment_date']          = DateTimeHelper::toRfc3339DateTime($this->originalPaymentDate);
        if (!empty($this->type)) {
            $json['type']                       = $this->type['value'];
        }
        $json['payment_method']                 = $this->paymentMethod;
        if (!empty($this->accrualAt)) {
            $json['accrual_at']                 = DateTimeHelper::toRfc3339DateTime($this->accrualAt['value']);
        }
        $json['created_at']                     = DateTimeHelper::toRfc3339DateTime($this->createdAt);
        if (!empty($this->liquidationArrangementId)) {
            $json['liquidation_arrangement_id'] = $this->liquidationArrangementId['value'];
        }
        $json['settlement_id']                  = $this->settlementId;
        $json['payment_profile_id']             = $this->paymentProfileId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
