<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

/**
 * Account settings of a payment link
 */
class GetPaymentLinkAccountSettingsResponse implements \JsonSerializable
{
    /**
     * @var array
     */
    private $merchantId = [];

    /**
     * @var array
     */
    private $merchantName = [];

    /**
     * @var array
     */
    private $accountId = [];

    /**
     * @var array
     */
    private $accountName = [];

    /**
     * @var array
     */
    private $accountType = [];

    /**
     * @var array
     */
    private $displayName = [];

    /**
     * @var array
     */
    private $organization = [];

    /**
     * Returns Merchant Id.
     */
    public function getMerchantId(): ?string
    {
        if (count($this->merchantId) == 0) {
            return null;
        }
        return $this->merchantId['value'];
    }

    /**
     * Sets Merchant Id.
     *
     * @maps merchant_id
     */
    public function setMerchantId(?string $merchantId): void
    {
        $this->merchantId['value'] = $merchantId;
    }

    /**
     * Unsets Merchant Id.
     */
    public function unsetMerchantId(): void
    {
        $this->merchantId = [];
    }

    /**
     * Returns Merchant Name.
     */
    public function getMerchantName(): ?string
    {
        if (count($this->merchantName) == 0) {
            return null;
        }
        return $this->merchantName['value'];
    }

    /**
     * Sets Merchant Name.
     *
     * @maps merchant_name
     */
    public function setMerchantName(?string $merchantName): void
    {
        $this->merchantName['value'] = $merchantName;
    }

    /**
     * Unsets Merchant Name.
     */
    public function unsetMerchantName(): void
    {
        $this->merchantName = [];
    }

    /**
     * Returns Account Id.
     */
    public function getAccountId(): ?string
    {
        if (count($this->accountId) == 0) {
            return null;
        }
        return $this->accountId['value'];
    }

    /**
     * Sets Account Id.
     *
     * @maps account_id
     */
    public function setAccountId(?string $accountId): void
    {
        $this->accountId['value'] = $accountId;
    }

    /**
     * Unsets Account Id.
     */
    public function unsetAccountId(): void
    {
        $this->accountId = [];
    }

    /**
     * Returns Account Name.
     */
    public function getAccountName(): ?string
    {
        if (count($this->accountName) == 0) {
            return null;
        }
        return $this->accountName['value'];
    }

    /**
     * Sets Account Name.
     *
     * @maps account_name
     */
    public function setAccountName(?string $accountName): void
    {
        $this->accountName['value'] = $accountName;
    }

    /**
     * Unsets Account Name.
     */
    public function unsetAccountName(): void
    {
        $this->accountName = [];
    }

    /**
     * Returns Account Type.
     */
    public function getAccountType(): ?string
    {
        if (count($this->accountType) == 0) {
            return null;
        }
        return $this->accountType['value'];
    }

    /**
     * Sets Account Type.
     *
     * @maps account_type
     */
    public function setAccountType(?string $accountType): void
    {
        $this->accountType['value'] = $accountType;
    }

    /**
     * Unsets Account Type.
     */
    public function unsetAccountType(): void
    {
        $this->accountType = [];
    }

    /**
     * Returns Display Name.
     */
    public function getDisplayName(): ?string
    {
        if (count($this->displayName) == 0) {
            return null;
        }
        return $this->displayName['value'];
    }

    /**
     * Sets Display Name.
     *
     * @maps display_name
     */
    public function setDisplayName(?string $displayName): void
    {
        $this->displayName['value'] = $displayName;
    }

    /**
     * Unsets Display Name.
     */
    public function unsetDisplayName(): void
    {
        $this->displayName = [];
    }

    /**
     * Returns Organization.
     */
    public function getOrganization(): ?string
    {
        if (count($this->organization) == 0) {
            return null;
        }
        return $this->organization['value'];
    }

    /**
     * Sets Organization.
     *
     * @maps organization
     */
    public function setOrganization(?string $organization): void
    {
        $this->organization['value'] = $organization;
    }

    /**
     * Unsets Organization.
     */
    public function unsetOrganization(): void
    {
        $this->organization = [];
    }

    /**
     * Converts the GetPaymentLinkAccountSettingsResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetPaymentLinkAccountSettingsResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetPaymentLinkAccountSettingsResponse',
            [
                'merchantId' => $this->getMerchantId(),
                'merchantName' => $this->getMerchantName(),
                'accountId' => $this->getAccountId(),
                'accountName' => $this->getAccountName(),
                'accountType' => $this->getAccountType(),
                'displayName' => $this->getDisplayName(),
                'organization' => $this->getOrganization()
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->merchantId)) {
            $json['merchant_id']   = $this->merchantId['value'];
        }
        if (!empty($this->merchantName)) {
            $json['merchant_name'] = $this->merchantName['value'];
        }
        if (!empty($this->accountId)) {
            $json['account_id']    = $this->accountId['value'];
        }
        if (!empty($this->accountName)) {
            $json['account_name']  = $this->accountName['value'];
        }
        if (!empty($this->accountType)) {
            $json['account_type']  = $this->accountType['value'];
        }
        if (!empty($this->displayName)) {
            $json['display_name']  = $this->displayName['value'];
        }
        if (!empty($this->organization)) {
            $json['organization']  = $this->organization['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
