<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Recipient response
 */
class GetRecipientResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $email;

    /**
     * @var string|null
     */
    private $document;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var \DateTime|null
     */
    private $createdAt;

    /**
     * @var \DateTime|null
     */
    private $updatedAt;

    /**
     * @var \DateTime|null
     */
    private $deletedAt;

    /**
     * @var GetBankAccountResponse|null
     */
    private $defaultBankAccount;

    /**
     * @var GetGatewayRecipientResponse[]|null
     */
    private $gatewayRecipients;

    /**
     * @var array<string,string>|null
     */
    private $metadata;

    /**
     * @var array
     */
    private $automaticAnticipationSettings = [];

    /**
     * @var array
     */
    private $transferSettings = [];

    /**
     * @var string|null
     */
    private $code;

    /**
     * @var string|null
     */
    private $paymentMode = 'bank_transfer';

    /**
     * Returns Id.
     * Id
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Id
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Name.
     * Name
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Name
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Email.
     * Email
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     * Email
     *
     * @maps email
     */
    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Document.
     * Document
     */
    public function getDocument(): ?string
    {
        return $this->document;
    }

    /**
     * Sets Document.
     * Document
     *
     * @maps document
     */
    public function setDocument(?string $document): void
    {
        $this->document = $document;
    }

    /**
     * Returns Description.
     * Description
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Description
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Type.
     * Type
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Type
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Status.
     * Status
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * Status
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Created At.
     * Creation date
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     * Creation date
     *
     * @maps created_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(?\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Updated At.
     * Last update date
     */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    /**
     * Sets Updated At.
     * Last update date
     *
     * @maps updated_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdatedAt(?\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Returns Deleted At.
     * Deletion date
     */
    public function getDeletedAt(): ?\DateTime
    {
        return $this->deletedAt;
    }

    /**
     * Sets Deleted At.
     * Deletion date
     *
     * @maps deleted_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDeletedAt(?\DateTime $deletedAt): void
    {
        $this->deletedAt = $deletedAt;
    }

    /**
     * Returns Default Bank Account.
     * Default bank account
     */
    public function getDefaultBankAccount(): ?GetBankAccountResponse
    {
        return $this->defaultBankAccount;
    }

    /**
     * Sets Default Bank Account.
     * Default bank account
     *
     * @maps default_bank_account
     */
    public function setDefaultBankAccount(?GetBankAccountResponse $defaultBankAccount): void
    {
        $this->defaultBankAccount = $defaultBankAccount;
    }

    /**
     * Returns Gateway Recipients.
     * Info about the recipient on the gateway
     *
     * @return GetGatewayRecipientResponse[]|null
     */
    public function getGatewayRecipients(): ?array
    {
        return $this->gatewayRecipients;
    }

    /**
     * Sets Gateway Recipients.
     * Info about the recipient on the gateway
     *
     * @maps gateway_recipients
     *
     * @param GetGatewayRecipientResponse[]|null $gatewayRecipients
     */
    public function setGatewayRecipients(?array $gatewayRecipients): void
    {
        $this->gatewayRecipients = $gatewayRecipients;
    }

    /**
     * Returns Metadata.
     * Metadata
     *
     * @return array<string,string>|null
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     * Metadata
     *
     * @maps metadata
     *
     * @param array<string,string>|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Returns Automatic Anticipation Settings.
     */
    public function getAutomaticAnticipationSettings(): ?GetAutomaticAnticipationResponse
    {
        if (count($this->automaticAnticipationSettings) == 0) {
            return null;
        }
        return $this->automaticAnticipationSettings['value'];
    }

    /**
     * Sets Automatic Anticipation Settings.
     *
     * @maps automatic_anticipation_settings
     */
    public function setAutomaticAnticipationSettings(
        ?GetAutomaticAnticipationResponse $automaticAnticipationSettings
    ): void {
        $this->automaticAnticipationSettings['value'] = $automaticAnticipationSettings;
    }

    /**
     * Unsets Automatic Anticipation Settings.
     */
    public function unsetAutomaticAnticipationSettings(): void
    {
        $this->automaticAnticipationSettings = [];
    }

    /**
     * Returns Transfer Settings.
     */
    public function getTransferSettings(): ?GetTransferSettingsResponse
    {
        if (count($this->transferSettings) == 0) {
            return null;
        }
        return $this->transferSettings['value'];
    }

    /**
     * Sets Transfer Settings.
     *
     * @maps transfer_settings
     */
    public function setTransferSettings(?GetTransferSettingsResponse $transferSettings): void
    {
        $this->transferSettings['value'] = $transferSettings;
    }

    /**
     * Unsets Transfer Settings.
     */
    public function unsetTransferSettings(): void
    {
        $this->transferSettings = [];
    }

    /**
     * Returns Code.
     * Recipient code
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * Sets Code.
     * Recipient code
     *
     * @maps code
     */
    public function setCode(?string $code): void
    {
        $this->code = $code;
    }

    /**
     * Returns Payment Mode.
     * Payment mode
     */
    public function getPaymentMode(): ?string
    {
        return $this->paymentMode;
    }

    /**
     * Sets Payment Mode.
     * Payment mode
     *
     * @maps payment_mode
     */
    public function setPaymentMode(?string $paymentMode): void
    {
        $this->paymentMode = $paymentMode;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']                                  = $this->id;
        $json['name']                                = $this->name;
        $json['email']                               = $this->email;
        $json['document']                            = $this->document;
        $json['description']                         = $this->description;
        $json['type']                                = $this->type;
        $json['status']                              = $this->status;
        $json['created_at']                          = DateTimeHelper::toRfc3339DateTime($this->createdAt);
        $json['updated_at']                          = DateTimeHelper::toRfc3339DateTime($this->updatedAt);
        $json['deleted_at']                          = DateTimeHelper::toRfc3339DateTime($this->deletedAt);
        $json['default_bank_account']                = $this->defaultBankAccount;
        $json['gateway_recipients']                  = $this->gatewayRecipients;
        $json['metadata']                            = $this->metadata;
        if (!empty($this->automaticAnticipationSettings)) {
            $json['automatic_anticipation_settings'] = $this->automaticAnticipationSettings['value'];
        }
        if (!empty($this->transferSettings)) {
            $json['transfer_settings']               = $this->transferSettings['value'];
        }
        $json['code']                                = $this->code;
        $json['payment_mode']                        = $this->paymentMode;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
