<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use stdClass;

/**
 * Split response
 */
class GetSplitResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $type;

    /**
     * @var int|null
     */
    private $amount;

    /**
     * @var array
     */
    private $recipient = [];

    /**
     * @var string|null
     */
    private $gatewayId;

    /**
     * @var array
     */
    private $options = [];

    /**
     * @var string|null
     */
    private $id;

    /**
     * Returns Type.
     * Type
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Type
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Amount.
     * Amount
     */
    public function getAmount(): ?int
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * Amount
     *
     * @maps amount
     */
    public function setAmount(?int $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Recipient.
     * Recipient
     */
    public function getRecipient(): ?GetRecipientResponse
    {
        if (count($this->recipient) == 0) {
            return null;
        }
        return $this->recipient['value'];
    }

    /**
     * Sets Recipient.
     * Recipient
     *
     * @maps recipient
     */
    public function setRecipient(?GetRecipientResponse $recipient): void
    {
        $this->recipient['value'] = $recipient;
    }

    /**
     * Unsets Recipient.
     * Recipient
     */
    public function unsetRecipient(): void
    {
        $this->recipient = [];
    }

    /**
     * Returns Gateway Id.
     * The split rule gateway id
     */
    public function getGatewayId(): ?string
    {
        return $this->gatewayId;
    }

    /**
     * Sets Gateway Id.
     * The split rule gateway id
     *
     * @maps gateway_id
     */
    public function setGatewayId(?string $gatewayId): void
    {
        $this->gatewayId = $gatewayId;
    }

    /**
     * Returns Options.
     */
    public function getOptions(): ?GetSplitOptionsResponse
    {
        if (count($this->options) == 0) {
            return null;
        }
        return $this->options['value'];
    }

    /**
     * Sets Options.
     *
     * @maps options
     */
    public function setOptions(?GetSplitOptionsResponse $options): void
    {
        $this->options['value'] = $options;
    }

    /**
     * Unsets Options.
     */
    public function unsetOptions(): void
    {
        $this->options = [];
    }

    /**
     * Returns Id.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['type']          = $this->type;
        $json['amount']        = $this->amount;
        if (!empty($this->recipient)) {
            $json['recipient'] = $this->recipient['value'];
        }
        $json['gateway_id']    = $this->gatewayId;
        if (!empty($this->options)) {
            $json['options']   = $this->options['value'];
        }
        $json['id']            = $this->id;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
