name: Lint PHP Syntax

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_php7_syntax:
    name: Check Syntax PHP v-7.1
    runs-on: small-runner
    container:
      image: php:7.1-apache
    steps:
    - 
      name: Checkout
      uses: stone-payments/approved-actions/actions/checkout/v4@stable
    -
      name: install system packages
      run: apt-get update && apt-get -y install zip git zlib1g-dev wget
    -
      name: Install PHP extensions
      run: |
        docker-php-ext-install pdo
        docker-php-ext-install zip
    -
      name: Display PHP Information
      run: php -v
    -
      name: Check PHP syntax
      run: php -l $(find . -name "*.php")

  check_php8_syntax:
    name: Check Syntax PHP v-8.5
    runs-on: small-runner
    container:
      image: php:8.5-apache
    steps:
    - 
      name: Checkout
      uses: stone-payments/approved-actions/actions/checkout/v4@stable
    -
      name: install system packages
      run: apt-get update && apt-get -y install libzip-dev
    -
      name: Install PHP extensions
      run: |
        docker-php-ext-install zip
        docker-php-ext-install pdo
    -
      name: Display PHP Information
      run: php -v
    -
      name: Check PHP syntax
      run: php -l $(find . -name "*.php")